version: '3'
services:
  web:
    build: .
    container_name: WSDock
    volumes:
      - server:/home
    stdin_open: true
    tty:  true
    ports:
      - "3000:3000"
volumes:
  server:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/myeochoi/goinfre
